### ISSUE TITLE
Эти конвертации точно нужны?

### ISSUE THREAD

**Issue by algolGuru** [myashaa/practice_TravelLine#11]
https://github.com/maria-usynina/practice_TravelLine/blob/d119c7039ae9098bbf2219b6e3a2448ca16b8fa1/ShopConsole/ShopConsole/Program.cs#L64
Мне кажется, без конвертаций тоже заведется, при условии того, что вы в базе данных верно таблицу создали

**Comment by algolGuru** [comment]
Но я не уверен, лучше отпишитесь

**Comment by maria-usynina** [comment]
![image](https://user-images.githubusercontent.com/79213041/114519099-ba2cab00-9c48-11eb-9f3f-a913ae65c654.png)

**Comment by algolGuru** [comment]
окей!
