### ISSUE TITLE
Пробел после BY

### ISSUE THREAD

**Issue by algolGuru** [myashaa/practice_TravelLine#13]
https://github.com/maria-usynina/practice_TravelLine/blob/d119c7039ae9098bbf2219b6e3a2448ca16b8fa1/ShopConsole/ShopConsole/Program.cs#L64
Мне кажется, без конвертаций тоже заведется, при условии того, что вы в базе данных верно таблицу создали

**Comment by maria-usynina** [comment]
![image](https://user-images.githubusercontent.com/79213041/114519859-81410600-9c49-11eb-8993-6dc5e6076c02.png)
